# Generated by Django 5.2.1 on 2025-05-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Жаңа'), ('processing', 'Қабылданды'), ('delivering', 'Жолда'), ('delivered', 'Жеткізілді')], default='new', max_length=20),
        ),
    ]
